# Default values for hello-chart.
# This is a YAML-formatted file.
autoscaling:
  enabled: false
replicaCount: 1

image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  # CHANGED: Switch to ClusterIP for Ingress Controller/AGIC
  type: ClusterIP 
  port: 80
  targetPort: 80
  
ingress:
  enabled: true # CHANGED: Enable ingress
  # IMPORTANT: This annotation tells AGIC to manage this Ingress resource
  annotations: 
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: /
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  # Change this host to a domain you own or a dummy domain for AGIC setup
  host: chart-example.local
  paths:
    - path: /
      pathType: Prefix
  tls:
    enabled: true
    secretName: chart-tls-secret

resources:
  # We usually recommend not to set defaults for limits and requests to keep them flexible
  # for the end-user.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
